lexik_jwt_authentication:
    secret_key: "%kernel.project_dir%/config/jwt/private.pem" # chemin vers ta clé privée
    public_key: "%kernel.project_dir%/config/jwt/public.pem" # chemin vers ta clé publique
    pass_phrase: "" # vide en dev car pas de mot de passe
    token_ttl: 3600
