<?php

namespace ContainerKicGzqL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScoreControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ScoreController' shared autowired service.
     *
     * @return \App\Controller\ScoreController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ScoreController.php';

        $container->services['App\\Controller\\ScoreController'] = $instance = new \App\Controller\ScoreController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\ScoreRepository'] ?? $container->load('getScoreRepositoryService')), ($container->privates['validator'] ?? $container->load('getValidatorService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ScoreController', $container));

        return $instance;
    }
}
