<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/api/register']], [], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/api/login']], [], [], []],
    'score_list' => [[], ['_controller' => 'App\\Controller\\ScoreController::list'], [], [['text', '/api/scores']], [], [], []],
    'score_create' => [[], ['_controller' => 'App\\Controller\\ScoreController::create'], [], [['text', '/api/scores']], [], [], []],
];
